version: "3.8"

services:
  app:
    container_name: ros2
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: ../
        target: /ros2_ws/
    tty: true
